# Generated by Django 5.0 on 2023-12-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_tagpost_women_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=45, unique=True),
        ),
    ]
